name: etiquette
description: Etiquette Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  dio_logging_interceptor: ^1.0.1
  hive_flutter: ^1.1.0
  fresh: ^0.4.1
  fresh_dio: ^0.3.2
  equatable: ^2.0.5
  fluttertoast: ^8.1.1
  flutter_svg: ^1.1.6
  chewie: ^1.3.6
  video_player: ^2.4.10
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  fonts:
    - family: RFDewi
      fonts:
        - asset: fonts/RFDewi/RFDewi-Thin.ttf
          weight: 100
        - asset: fonts/RFDewi/RFDewi-Ultralight.ttf
          weight: 200
        - asset: fonts/RFDewi/RFDewi-Light.ttf
          weight: 300
        - asset: fonts/RFDewi/RFDewi-Regular.ttf
          weight: 400
        - asset: fonts/RFDewi/RFDewi-Semibold.ttf
          weight: 500
        - asset: fonts/RFDewi/RFDewi-Semibold.ttf
          weight: 600
        - asset: fonts/RFDewi/RFDewi-Bold.ttf
          weight: 700
        - asset: fonts/RFDewi/RFDewi-Ultrabold.ttf
          weight: 800
        - asset: fonts/RFDewi/RFDewi-Black.ttf
          weight: 900
    - family: Geometria
      fonts:
        - asset: fonts/Geometria/geometria_light.otf
          weight: 100
        - asset: fonts/Geometria/geometria_light.otf
          weight: 200
        - asset: fonts/Geometria/geometria_light.otf
          weight: 300
        - asset: fonts/Geometria/geometria_lightitalic.otf
          weight: 100
          style: italic
        - asset: fonts/Geometria/geometria_lightitalic.otf
          weight: 200
          style: italic
        - asset: fonts/Geometria/geometria_lightitalic.otf
          weight: 300
          style: italic
        - asset: fonts/Geometria/geometria_medium.otf
          weight: 400
        - asset: fonts/Geometria/geometria_medium.otf
          weight: 500
        - asset: fonts/Geometria/geometria_mediumitalic.otf
          weight: 400
          style: italic
        - asset: fonts/Geometria/geometria_mediumitalic.otf
          weight: 500
          style: italic
        - asset: fonts/Geometria/geometria_bold.otf
          weight: 600
        - asset: fonts/Geometria/geometria_bold.otf
          weight: 700
        - asset: fonts/Geometria/geometria_bolditalic.otf
          weight: 600
          style: italic
        - asset: fonts/Geometria/geometria_bolditalic.otf
          weight: 700
          style: italic
        - asset: fonts/Geometria/geometria_extrabold.otf
          weight: 800
        - asset: fonts/Geometria/geometria_extrabold.otf
          weight: 900

  uses-material-design: true

  assets:
      - assets/